id: P009487
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG12153
  title: དམ་ཆོས་སྣང་བའི་སྒྲོན་མེ།
  author: ''
  volumes:
    5c35d782a967438d8a0c83079af13fa5:
      image_group_id: I1KG12155
      title: ''
      volume_number: 1
      total_pages: 143
      base_file: v001.txt
